// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package devs

import (
	"time"
)

type Dev struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Password     string    `json:"password"`
	Skills       []string  `json:"skills"`
	Bio          string    `json:"bio"`
	Availability bool      `json:"availability"`
	Socials      []string  `json:"socials"`
	CreatedAt    time.Time `json:"created_at"`
}
